# Generated by Django 5.0.1 on 2024-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0009_student_detalis_id_card_student_detalis_payment_ss'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'abc',
            },
        ),
        migrations.RenameField(
            model_name='events_detalis',
            old_name='event_id',
            new_name='roll',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='payment_ss',
        ),
        migrations.AddField(
            model_name='event',
            name='eventName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
