# Generated by Django 5.0.1 on 2024-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0011_abc_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abc',
            name='eventName',
        ),
        migrations.AddField(
            model_name='abc',
            name='CatWalk',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='DuoDance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='Facepaint',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='mintoframe',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='rell',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abc',
            name='selfie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
