# Generated by Django 5.0.1 on 2024-03-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0012_remove_abc_eventname_abc_catwalk_abc_duodance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='CatWalk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abc',
            name='DuoDance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='abc',
            name='Facepaint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abc',
            name='mintoframe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abc',
            name='rell',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abc',
            name='selfie',
            field=models.IntegerField(default=0),
        ),
    ]
