# Generated by Django 5.0.1 on 2024-03-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0013_alter_abc_catwalk_alter_abc_duodance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='DuoDance',
            field=models.IntegerField(default=0),
        ),
    ]
